### PR TITLE
Completed login page 

### PR DESCRIPTION
**Pull request by Sumanthsharm**
@SumanthSharma2705 please review code

### CODE REVIEW

**Review by SumanthSharma2705 — COMMENTED** [review]
@Sumanthsharm image size is quite big set the width to 20%

**Comment by Sumanthsharm** [comment]
> @Sumanthsharm image size is quite big set the width to 20%

@SumanthSharma2705 image width se as requested 20%

**Review by Sumanthsharm — COMMENTED** [review]
good job

**Review by SumanthSharma2705 — APPROVED** [review]
@Sumanthsharm good job

**Pull request merged**
